/** Curated Regal AI highlights for the dashboard. */
export const DASHBOARD_REGAL_TOOLS = [
  {
    slug: "math-solver",
    href: "/tools/math-solver",
    name: "Math Solver",
    description: "Step-by-step algebra, calculus, geometry & physics",
    icon: "Sigma",
    regalAI: true,
  },
  {
    slug: "my-courses",
    href: "/my-courses",
    name: "My Courses",
    description: "AI-generated lessons & materials for every subject",
    icon: "GraduationCap",
    regalAI: true,
  },
  {
    slug: "tutor",
    href: "/tools/tutor",
    name: "Regal AI Tutor",
    description: "24/7 conversational academic tutor",
    icon: "MessagesSquare",
    regalAI: true,
  },
  {
    slug: "research",
    href: "/research",
    name: "Research Lab",
    description: "Upload sources, summarize & chat with your research",
    icon: "Brain",
    regalAI: true,
  },
  {
    slug: "study-planner",
    href: "/tools/study-planner",
    name: "Study Planner",
    description: "Personalized weekly study schedules",
    icon: "CalendarDays",
    regalAI: true,
  },
  {
    slug: "plagiarism",
    href: "/tools/plagiarism",
    name: "Plagiarism Check",
    description: "Scan writing for originality issues",
    icon: "ShieldCheck",
    regalAI: true,
  },
  {
    slug: "quiz",
    href: "/tools/quiz",
    name: "Quiz Generator",
    description: "Auto-generate practice quizzes from notes",
    icon: "HelpCircle",
    regalAI: true,
  },
  {
    slug: "essay-planner",
    href: "/tools/essay-planner",
    name: "Essay Planner",
    description: "Plan structure, then auto-generate your full essay",
    icon: "PenLine",
    regalAI: true,
  },
  {
    slug: "continuous-cv",
    href: "/continuous-cv",
    name: "Continuous CV",
    description: "Build your living CV & export a beautiful PDF",
    icon: "FileUser",
    regalAI: true,
  },
] as const;
